// Generated by npm run screenshots:sync.
export const screenshotVersions: Record<string, string> = {
  "/media/app-accueil.png": "6582ffc425a7",
  "/media/app-carte.png": "c16b75197af6",
  "/media/app-compagnon.png": "d8caed57cdec",
  "/media/app-idees.png": "56e706703df7",
  "/media/app-moments.png": "0836abe8742a",
  "/media/app-party-expenses.png": "95c2145e43ee",
  "/media/app-rituels.png": "654a641af7bb",
  "/media/app-party.png": "5b89045aac24",
  "/media/app-party-lab.png": "de808564d0b2",
  "/media/app-party-photos.png": "6fefbb4a8e3b",
  "/media/app-spicy-home.png": "2fc6c1d8f26c",
  "/media/app-spicy-vault.png": "6977728f0448"
};
